<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Carter" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Scalar.AspNetCore" Version="2.16.16" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Zempler.Ticketing.Domain\Zempler.Ticketing.Domain.csproj" />
    <ProjectReference Include="..\Zempler.Ticketing.Application\Zempler.Ticketing.Application.csproj" />
    <ProjectReference Include="..\Zempler.Ticketing.Infrastructure\Zempler.Ticketing.Infrastructure.csproj" />
  </ItemGroup>
</Project>